# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server/telegram_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('server/*.py', 'server'),
        ('server/requirements.txt', 'server'),
    ],
    hiddenimports=[
        'telethon',
        'telethon.sync',
        'telethon.sessions',
        'telethon.errors',
        'flask',
        'flask_cors',
        'nest_asyncio',
        'socks',
        'cryptg',
        'PIL',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.utils',
        'werkzeug.security',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'dotenv',
        'asyncio',
        'ssl',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='telegram_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico'
)